/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.DrugMinistry;

import Business.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.SystemAdminWorkArea.SystemAdminManagePharmacy;

/**
 *
 * @author HOME
 */
public class DrugAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GovModulesJPanel
     */
   private JPanel userProcessContainerSAWAP;
   private EcoSystem ecosystemSAWAP;
    
    public DrugAdminJPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        
        initComponents();
        this.userProcessContainerSAWAP = userProcessContainer;
        this.ecosystemSAWAP = ecosystem;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_DrugTesting = new javax.swing.JButton();

        btn_DrugTesting.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_DrugTesting.setText("DRUG TESTING");
        btn_DrugTesting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DrugTestingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btn_DrugTesting, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(btn_DrugTesting, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DrugTestingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DrugTestingActionPerformed
       // TODO add your handling code here:
      DrugApprovalJPanel daj = new DrugApprovalJPanel(userProcessContainerSAWAP, ecosystemSAWAP);
        userProcessContainerSAWAP.add("UserSupplier", daj);
        CardLayout layout = (CardLayout)this.userProcessContainerSAWAP.getLayout();
        layout.next(userProcessContainerSAWAP);
    }//GEN-LAST:event_btn_DrugTestingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DrugTesting;
    // End of variables declaration//GEN-END:variables
}
