/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.DrugMinistry;

import Business.EcoSystem;
import Business.Drugs.Drugs;
import Business.Drugs.DrugsDirectory;
//import Business.Supplier.Supplier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HOME
 */
public class DrugApprovalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RawMaterialJPanel
     */
    private JPanel UserProccessContainerSAMC;
    private EcoSystem ecosystem;
   
    public DrugApprovalJPanel(JPanel userProccessContainer, EcoSystem ecosystem) {
        initComponents();
        this.UserProccessContainerSAMC = userProccessContainer;
        this.ecosystem = ecosystem;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_drug = new javax.swing.JTextField();
        txt_Components = new javax.swing.JTextField();
        btn_Publish = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DrugApproval = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txt_Id = new javax.swing.JTextField();
        text_disease = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Health Ministry");

        jLabel2.setText("Drug");

        jLabel3.setText("Components");

        txt_drug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_drugActionPerformed(evt);
            }
        });

        txt_Components.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ComponentsActionPerformed(evt);
            }
        });

        btn_Publish.setText("List");
        btn_Publish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PublishActionPerformed(evt);
            }
        });

        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tbl_DrugApproval.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "DRUG", "Components", "Disease"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_DrugApproval);

        jLabel4.setText("ID");

        txt_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdActionPerformed(evt);
            }
        });

        jLabel5.setText("Disease");

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Publish)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(82, 82, 82)
                                    .addComponent(txt_Components, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                    .addGap(82, 82, 82)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(text_disease, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                                        .addComponent(txt_drug)
                                        .addComponent(txt_Id)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_disease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_drug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Components, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23)
                .addComponent(btn_Publish)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_drugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_drugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_drugActionPerformed

    private void txt_ComponentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ComponentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ComponentsActionPerformed

    private void txt_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_DrugApproval.getSelectedRow();
        if (selectedRow >= 0)
        {
            Drugs selectedDrugs = (Drugs) tbl_DrugApproval.getValueAt(selectedRow, 1);
            ecosystem.getDrugsDirectory().deleteDrugs(selectedDrugs);
            JOptionPane.showMessageDialog(null, "Drugs " + selectedDrugs.getDrugName()+ " deleted successfully!");
            populateTable();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please select a row!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_PublishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PublishActionPerformed
        // TODO add your handling code here:
        Drugs pe = ecosystem.getDrugsDirectory().createDrugs(txt_Id.getText(),txt_drug.getText(),txt_Components.getText(), text_disease.getText());
        System.out.println(pe);
      //  supplier se = new supplier(pe);
        if(pe == null)
        {
            JOptionPane.showMessageDialog(null,"Drugs " + txt_drug.getText() + " already exists!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Drugs successfully Published ");
            
        }
         txt_Id.setText("");
         txt_drug.setText("");
         text_disease.setText("");
         txt_Components.setText("");
         
        populateTable();
    }//GEN-LAST:event_btn_PublishActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         DefaultTableModel model= (DefaultTableModel) tbl_DrugApproval.getModel();
        if(tbl_DrugApproval.getSelectedRowCount()==1){
            
           int selectedRowIndex = tbl_DrugApproval.getSelectedRow();
           //DefaultTableModel model1 = (DefaultTableModel) tbl_SA_PatientDirectory.getModel();
           Drugs selectedDrugs_Details  = (Drugs) model.getValueAt(selectedRowIndex, 1);
         //  int row = DrugsDirectory.getDru().indexOf(selectedPatientD_Details);
           
         selectedDrugs_Details.setDrugName(txt_drug.getText());
         selectedDrugs_Details.setDrugCompostion(txt_Components.getText());
         selectedDrugs_Details.setDisease(text_disease.getText());
         selectedDrugs_Details.setId(txt_Id.getText());
        }
        
        populateTable();
        txt_Id.setText("");
        txt_drug.setText("");
        text_disease.setText("");
        txt_Components.setText("");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Publish;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_DrugApproval;
    private javax.swing.JTextField text_disease;
    private javax.swing.JTextField txt_Components;
    private javax.swing.JTextField txt_Id;
    private javax.swing.JTextField txt_drug;
    // End of variables declaration//GEN-END:variables

private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel)tbl_DrugApproval.getModel();
        dtm.setRowCount(0); //deletes the empty records  
        int count1 = 1;
        if(ecosystem.getDrugsDirectory().getDrugsList()!= null)
        {
            for(Drugs s : ecosystem.getDrugsDirectory().getDrugsList())
            {
                Object[] row = new Object[dtm.getColumnCount()]; //creates an array
                row[0] = s.getId();
                row[1] = s;
                row[2] = s.getDrugCompostion();
                row[3] = s.getDisease();
                dtm.addRow(row);
                count1++;
            }
        }
        else
        {
            tbl_DrugApproval.setEnabled(false);
        }
    }




}
